ds/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic import TemplateView, RedirectView

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^posrednicy/', include('profiles.urls', namespace='profiles')),
    url(r'^accounts/profile/$', RedirectView.as_view(pattern_name='panel', permanent=False)),
    url(r'^$', views.home, name='home'),
    url(r'^o-nas/$', views.about, name='about'),
    url(r'^kontakt/$', views.contact, name='contact'),
    url(r'^panel/$', views.panel, name='panel'),
    url(r'^polityka-prywatnosci/$', views.policy, name='policy'),
    url(r'^regulamin/$', views.toc, name='toc'),
] 

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView

from . import views

app_name = 'profiles'
urlpatterns = [
	url(r'^$', views.profile_list, name='list'),
	url(r'^kontakt-doradca/$', views.message_to_consultant, name='ask_consultant'),
	url(r'^(?P<pk>\d+)/$', views.profile_detail, name='detail'),
	url(r'^(?P<pk>\d+)/edit/$', views.edit_profile, name='edit'),
	url(r'^(?P<pk>\d+)/opinia/$', views.add_review, name='add_review'),
	url(r'^(?P<pk>\d+)/kontakt-doradca/$', views.inquiry, name='inquiry'),
	url(r'^\d+/password/$', RedirectView.as_view(pattern_name='account_change_password', permanent=False))
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.core.exceptions import ValidationError


class Profile(models.Model):

	def validate_image(fieldfile_obj):
		filesize = fieldfile_obj.file.size
		megabyte_limit = 1
		if filesize > megabyte_limit*1024*1024:
			raise ValidationError("Zbyt duży rozmiar pliku. Użyj zdjęcia o rozmiarze poniżej %sMB" % str(megabyte_limit))

	user = models.OneToOneField(User, blank=True, null=True)
	avatar = models.ImageField(upload_to='avatar', blank=True, validators=[validate_image])
	description = models.TextField(blank=True)
	city = models.CharField(max_length=100, blank=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def get_approved_reviews(self):
		return self.review_set.filter(approved="True")

	def get_inquiries(self):
		return self.inquiry_set.all()	

	def __str__(self):
		return self.user.get_full_name()

class Review(models.Model): 
	profile = models.ForeignKey(Profile)
	pub_date = models.DateTimeField(auto_now=False, auto_now_add=True)
	name = models.CharField(max_length=254)
	email = models.EmailField(max_length=254)
	company = models.CharField(max_length=254, blank=True, null=True)
	position = models.CharField(max_length=254, blank=True, null=True)
	message = models.TextField()
	approved = models.BooleanField(default=False)

class Inquiry(models.Model):
	profile = models.ForeignKey(Profile)
	pub_date = models.DateTimeField(auto_now=False, auto_now_add=True)
	name = models.CharField(max_length=254)
	email = models.EmailField(max_length=254)
	tel = models.CharField(max_length=254, blank=True)
	message = models.TextField()


def create_profile(sender, **kwargs):
	if kwargs['created']:
		profile = Profile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

profiles/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

from .models import Profile, Review, Inquiry

class ProfileForm(ModelForm):
	class Meta:
		model = Profile
		fields = ('avatar', 'description','city')

		labels = {
            'description': 'Opis',
            'city': 'Miasto',
        }

class ReviewForm(ModelForm):
	class Meta:
		model = Review
		fields = ('name', 'email', 'company', 'position', 'message')

		labels = {
			'name': 'Imię i Nazwisko',
			'email': 'E-Mail',
			'company': 'Firma',
			'position': 'Rola w firmie',
			'message': 'Opinia',
		}

class InquiryForm(ModelForm):
	class Meta:
		model = Inquiry
		fields = ('name', 'email', 'tel', 'message')

		labels = {
			'name': 'Imię i Nazwisko',
			'email': 'E-Mail',
			'tel': 'Telefon',
			'message': 'Wiadomość',
		}


class AccountForm(UserChangeForm):
	class Meta:
		model = User
		fields = ('first_name','last_name', 'password')

		widgets = {
            'first_name': TextInput(attrs={'placeholder': 'Imię'}),
        }


class MessageForm(forms.Form):
	user = User.objects.all()

	client = forms.CharField(
		label=_("Twoje imię i nazwisko"),
		widget=forms.TextInput,
		required=True,
	)
	email = forms.EmailField(
		label=_("Email kontaktowy"),
		
		required=True,
	)
	tel = forms.CharField(
		label=_("Telefon"),
		widget=forms.TextInput,
		required=False,
	)
	recipient = forms.ModelChoiceField(
		label=_("Wybierz doradcę nieruchomości"),
		queryset=Profile.objects.filter(city__gt='', description__gt=''),
		required=False,
	)
	message = forms.CharField(
		label=_("Wiadomość"),
		widget=forms.Textarea,
		required=True,
	)

	def __init__(self, request, *args, **kwargs):
		super(MessageForm, self).__init__(*args, **kwargs)
		self.request = request
		self.fields["recipient"].queryset = \
			self.fields["recipient"].queryset.\
			exclude(pk=request.user.pk)

	def save(self):
		cleaned_data = self.cleaned_data
		send_mail(
			subject=ugettext("A message from %s") % \
				'ZnajdźMiDom',
			message=cleaned_data["message"],
			from_email='biuro@idealnyposrednik.pl',
			recipient_list=[
				'biuro@idealnyposrednik.pl',
			],
			fail_silently=True,
		)

profiles/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail
from django.contrib.auth.models import User

from .models import Profile, Review, Inquiry
from .forms import ProfileForm, AccountForm, ReviewForm, InquiryForm, MessageForm
from .filters import ProfileFilter

# Create your views here.
def profile_list(request):
	profile_list = Profile.objects.filter(city__gt='', description__gt='').order_by('?')
	profile_filter = ProfileFilter(request.GET, queryset=profile_list)
	return render(request, 'profiles/profile_list.html', {'filter': profile_filter})

def profile_detail(request, pk):
	profile = get_object_or_404(Profile, pk=pk)
	return render(request, 'profiles/profile_detail.html', {'profile': profile,})

@login_required
def edit_profile(request, pk):
	
	profile = Profile.objects.get(pk=pk)
	user = request.user

	if profile.user != request.user:
		raise Http404

	if request.method == 'POST':

	    p = ProfileForm(request.POST, request.FILES, instance=profile)
	    u = AccountForm(request.POST, instance=user )
	    
	    if p.is_valid() and u.is_valid():
	    	p.save()
	    	u.save()
	    	messages.success(request, 'Profil zaktualizowany')
	    	return redirect('profiles:detail', pk=profile.pk)
	else:
	    p = ProfileForm(instance=profile)
	    u = AccountForm(instance=user)
	return render(request, 'profiles/edit_profile.html', {'profile': profile, 'form_profile': p, 'form_user': u})

def add_review(request, pk):
	profile = get_object_or_404(Profile, pk=pk)

	if request.method == 'POST':

		form = ReviewForm(request.POST, instance=profile)
		if form.is_valid():
			name = form.cleaned_data['name']
			email = form.cleaned_data['email']
			company = form.cleaned_data['company']
			position = form.cleaned_data['position']
			message = form.cleaned_data['message']

			review = Review()
			review.profile = profile
			review.name = name
			review.email = email
			review.company = company
			review.position = position
			review.message = message

			review.save()
			messages.success(request, 'Opinia dodana. Pojawi się na profilu po zatwierdzeniu przez administratora.')
			send_mail(
			subject="Nowa opinia na %s" % \
				'Idealny Pośrednik',
			message=company,
			from_email='biuro@idealnyposrednik.pl',
			recipient_list=[
				profile.user.email,
			],
			fail_silently=True,
		)

			# Always return an HttpResponseRedirect after successfully dealing
			# with POST data. This prevents data from being posted twice if a
			# user hits the Back button.
			return redirect('profiles:detail', pk=profile.pk)

	else:
		form = ReviewForm(instance=profile)         

	return render(request, 'profiles/review.html', {'profile': profile, 'form': form})

def inquiry(request, pk):
	profile = get_object_or_404(Profile, pk=pk)

	if request.method == 'POST':

		form = InquiryForm(request.POST, instance=profile)
		if form.is_valid():
			name = form.cleaned_data['name']
			email = form.cleaned_data['email']
			tel = form.cleaned_data['tel']
			message = form.cleaned_data['message']

			inquiry = Inquiry()
			inquiry.profile = profile
			inquiry.name = name
			inquiry.email = email
			inquiry.tel = tel
			inquiry.message = message

			inquiry.save()
			messages.success(request, 'Wiadomość została wysłana, wkrótce odezwie się doradca.')
			send_mail(
			subject="Nowa wiadomość na %s" % \
				'ZnajdźMiDom',
			message="Zaloguj się na ZnajdzMiDom, aby odczytać wiadomość, i otrzymać dane potencjalnego klienta.",
			from_email='no-reply@znajdzmidom.pl',
			recipient_list=[
				profile.user.email,
			],
			fail_silently=True,
		)

			# Always return an HttpResponseRedirect after successfully dealing
			# with POST data. This prevents data from being posted twice if a
			# user hits the Back button.
			return redirect('profiles:detail', pk=profile.pk)

	else:
		form = InquiryForm(instance=profile)         

	return render(request, 'profiles/inquiry.html', {'profile': profile, 'form': form})	


def message_to_consultant(request):
   if request.method == "POST":
       form = MessageForm(request, data=request.POST)
       if form.is_valid():
           form.save()
           messages.success(request, 'Wiadomość wysłana')
           return redirect('profiles:list')
   else:
       form = MessageForm(request)

   return render(request, "profiles/contact_consultant.html", {"form": form}
   )

profiles/templates/profiles/contact_consultant.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}Zapytaj doradcę {{ block.super }}{% endblock %}

{% block content%}
<section id="page" class="pico">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <div class="block wow fadeInLeft" data-wow-delay=".3s" data-wow-duration="500ms">
                    <h2>
                    Zapytaj doradcę nieruchomości
                    </h2>
                         {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    <p>									
                    	<form role="form" action="" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-default">Zapytaj doradcę</button>
                            <span style="padding-left: 50px">* pola wymagane</span>
                        </form>
                    </p>
              
                </div>            
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="block wow fadeInRight" data-wow-delay=".3s" data-wow-duration="500ms">
                    <img class="review" src="{% static 'images/zdm-rejestracja.jpg' %}" alt="">
                </div>
                
            </div>
            
        </div>
    </div>
</section>
{% endblock %}

profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ profile.user.get_full_name }} {{ block.super }}{% endblock %}

{% block content%}
         <section id="page">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="block wow fadeInLeft" data-wow-delay=".3s" data-wow-duration="500ms">
                                <h2>
                                Edycja: {{ profile.user.get_full_name }}
                                </h2>
                                <p>									
                                	<form role="form" action="" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form_user|crispy }}
                                        {{ form_profile|crispy }}

                                        <button type="submit" class="btn btn-default">Zaktualizuj dane</button>
                                    </form>
                                </p>
                          
                            </div>
                            
                        </div>
                        
                    </div>
                </div>
            </section>
{% endblock %}

profiles/templates/profiles/inquiry.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ profile.user.get_full_name }} {{ block.super }}{% endblock %}

{% block content%}
         <section id="page" class="pico">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="block wow fadeInLeft" data-wow-delay=".3s" data-wow-duration="500ms">
                                <h2>
                                Zapytaj doradcę: {{ profile.user.get_full_name }}
                                </h2>
                                     {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                                <p>									
                                	<form role="form" action="" method="post">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <button type="submit" class="btn btn-default">Wyślij wiadomość</button>
                                    </form>
                                </p>
                          
                            </div>
                            
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="block wow fadeInRight" data-wow-delay=".3s" data-wow-duration="500ms">
                                <img class="review" src="{% static 'images/zdm-rejestracja.jpg' %}" alt="">
                            </div>
                            
                        </div>
                        
                    </div>
                </div>
            </section>
{% endblock %}

profiles/templates/profiles/profile_detail.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ profile.user.get_full_name }} {{ block.super }}{% endblock %}

{% block content%}
<section id="page">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="block wow fadeInDown" data-wow-delay=".2s" data-wow-duration="500ms">
                    <div class="col-md-3 col-sm-3">
                    {% if profile.avatar %}
					   <img src="{{ profile.avatar|thumbnail_url:'avatar' }}" id="profil" class="img-responsive" alt="{{ profile.user.get_full_name }}" width=400>     
                    {% else %}
                        <img src="{% static 'images/avatar-default.jpg' %}" id="profil" class="img-responsive" alt="{{ profile.user.get_full_name }}" width=400> 
                    {% endif %}  
                    <div style="margin-top: 15px; ">
                        {% if user == profile.user %}
                        <a href="{% url 'profiles:edit' pk=profile.pk%}" class="btn btn-block btn-default" role="button">Edytuj opis</a>
                        {% endif %}  
                        <br>
                        <!--<a href="{% url 'profiles:inquiry' pk=profile.pk %}" class="btn btn-block btn-default">Zapytaj doradcę</a>
                        <br>-->
                        <a href="{% url 'profiles:add_review' pk=profile.pk %}" class="btn btn-block btn-default" role="button"> Dodaj opinię</a>  
                    </div>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <h3> {{ profile.user.get_full_name }} </h3>
                        {% if profile.city %}
                        <h4> {{ profile.city }} </h4>
                        {% endif %}
                        {% if profile.description %}
                        <p>
                            {{ profile.description}}
                        </p>
                        {% endif %}
                        <!-- Opinie -->
                        <h3 >Opinie({{ profile.get_approved_reviews.count }}):</h3>
                        {% if profile.get_approved_reviews %}
                        <div class="quote"><i class="fa fa-quote-left fa-4x"></i></div>
                        <div class="carousel slide" id="fade-quote-carousel" data-ride="carousel" data-interval="10000">
                          <!-- Carousel indicators -->
                            <ol class="carousel-indicators">
                            {% for review in profile.get_approved_reviews %}   
                                {% if forloop.first %}
                                    <li data-target="#fade-quote-carousel" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                                {% else %}
                                    <li data-target="#fade-quote-carousel" data-slide-to="{{ forloop.counter0 }}"></li>
                                {% endif %}
                            {% endfor %}
                            </ol>
                            <!-- Carousel items -->
                            <div class="carousel-inner">
                            {% for review in profile.get_approved_reviews %}
                                {% if forloop.first %}
                                <div class="active item"> 
                                    <blockquote>
                                        <em>{{ review.message }}</em>
                                        <br><strong>{{ review.name }}</strong>
                                    </blockquote>   
                                </div>
                                {% else %}
                                 <div class="item">
                                    <blockquote>
                                        <em>{{ review.message }}</em>
                                        <br><strong>{{ review.name }}</strong>
                                    </blockquote>   
                                </div>
                                {% endif %}
                            {% endfor %}
                            </div>
                        </div>
                        {% else %}
                         <p>Ten doradca nie otrzymał jeszcze opini.</p>
                        {% endif %}
                    </div>      
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

profiles/templates/profiles/profile_list.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load thumbnail %}

{% block title %}Doradcy {{ block.super }}{% endblock %}

{% block content%}
<section id="page">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="block wow fadeInLeft" data-wow-delay=".3s" data-wow-duration="500ms">
                    <h2>
                    Pośrednicy nieruchomości
                    </h2>
                    <!--<form method="get">
                        {{ filter.form|crispy }}
                         <button type="submit" class="btn btn-default">Szukaj</button>
                         <a href="{% url 'profiles:list' %}" class="btn btn-default">Resetuj</a>
                    </form>-->

                    <form method="get">
                    
                        <div class="row">
                          <!--  <div class="form-group col-md-3 col-sm-3">
                              {{ filter.form.user__first_name.label_tag }}
                              {% render_field filter.form.user__first_name class="form-control" %}
                            </div> -->
                            <div class="form-group col-md-5 col-sm-5">
                              {{ filter.form.user__last_name.label_tag }}
                              {% render_field filter.form.user__last_name class="form-control" %}
                            </div>
                            <div class="form-group col-md-4 col-sm-4">
                              {{ filter.form.city.label_tag }}
                              {% render_field filter.form.city class="form-control" %}
                            </div>
                            <div class="form-group col-md-3 col-sm-3">
                                <div class="filter-btns">
                                    <button type="submit" class="btn btn-default orange">Wyszukaj</button>
                                    <a href="{% url 'profiles:list' %}" class="btn btn-default orange">Resetuj</a>
                                </div>
                            </div>
                        </div>
                    
                    </form>    

                    <p>
                        {% for profile in filter.qs|slice:":24" %}
                        <div class="col-md-3 col-sm-6 profile-list-item">
                        {% if profile.avatar %}
                        <a href="{% url 'profiles:detail' pk=profile.pk %}">
                            <img src="{{ profile.avatar|thumbnail_url:'avatar' }}" class="img-responsive" alt="{{ profile.user.get_full_name }}" width=400></a>
                        
                        {% else %}
                        <a href="{% url 'profiles:detail' pk=profile.pk %}">
                            <img src="{% static 'images/avatar-default.jpg' %}"  class="img-responsive" alt="{{ profile.user.get_full_name }}" width=400>
                        </a>
                       
                        {% endif %}    
                            <h3><a href="{% url 'profiles:detail' pk=profile.pk %}">{{ profile.user.get_full_name }}</a></h3>
                            {% if profile.city %}
                            <h4> {{ profile.city }}</h4>
                            {% endif %}
                            
                            <p class="profile-description-list">{{ profile.description|truncatewords_html:22 }}</p>
                           
                            <a href="{% url 'profiles:detail' pk=profile.pk %}" class="profil-link">Przejdź do pełnego profilu</a>
                        </div> 

                        {% endfor %}
                    </p>
              
                </div>
                
            </div>
            
        </div>
    </div>
</section> <!-- /#about -->
{% endblock %}

profiles/templates/profiles/review.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ profile.user.get_full_name }} {{ block.super }}{% endblock %}

{% block content%}
         <section id="page" class="pico">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-6 vbottom">
                            <div class="block wow fadeInLeft" data-wow-delay=".3s" data-wow-duration="500ms">
                                <h2>
                                Opinia dla {{ profile.user.get_full_name }}
                                </h2>
                                     {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                                <p>									
                                	<form role="form" action="" method="post">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <button type="submit" class="btn btn-default">Dodaj opinię</button>
                                    </form>
                                </p>
                          
                            </div>
                            
                        </div><!--
                        --><div class="col-md-6 col-sm-6 vbottom">
                            <div class="block wow fadeInRight" data-wow-delay=".3s" data-wow-duration="500ms">
                                <img class="review" src="{% static 'images/zmd-formularz.jpg' %}" alt="">
                            </div>
                            
                        </div>
                        
                    </div>
                </div>
            </section> <!-- /#about -->
{% endblock %}