ds/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic import TemplateView, RedirectView

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^posrednicy/', include('profiles.urls', namespace='profiles')),
    url(r'^accounts/profile/$', RedirectView.as_view(pattern_name='panel', permanent=False)),
    url(r'^$', views.home, name='home'),
    url(r'^o-nas/$', views.about, name='about'),
    url(r'^kontakt/$', views.contact, name='contact'),
    url(r'^panel/$', views.panel, name='panel'),
    url(r'^polityka-prywatnosci/$', views.policy, name='policy'),
    url(r'^regulamin/$', views.toc, name='toc'),
] 

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView

from . import views

app_name = 'profiles'
urlpatterns = [
	url(r'^$', views.profile_list, name='list'),
	url(r'^kontakt-doradca/$', views.message_to_consultant, name='ask_consultant'),
	url(r'^(?P<pk>\d+)/$', views.profile_detail, name='detail'),
	url(r'^(?P<pk>\d+)/edit/$', views.edit_profile, name='edit'),
	url(r'^(?P<pk>\d+)/opinia/$', views.add_review, name='add_review'),
	url(r'^(?P<pk>\d+)/kontakt-doradca/$', views.inquiry, name='inquiry'),
	url(r'^\d+/password/$', RedirectView.as_view(pattern_name='account_change_password', permanent=False))
]

templates/about.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %}O Nas {{ block.super }}{% endblock %}

{% block content%}
         <section id="page" class="pico">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 vbottom">
                            <div class="block wow fadeInLeft" data-wow-delay=".3s" data-wow-duration="500ms">
                                <h2>
                                O nas
                                </h2>
                                
                                <p>
                                    Idealny Pośrednik to innowacyjne rozwiązanie na rynku nieruchomości. Platforma skupia najlepszych pośredników nieruchomości z branży oraz zainteresowanych zakupem mieszkania, lokalu czy działki. Indywidualnie przygotowane oferty to pewność, że znajdziesz dokładnie to, czego szukasz oszczędzając przy tym czas. Indywidualny Dorada pomoże Ci załatwić wszelkie formalności oraz odpowie na każde Twoje pytanie.


                                </p>
                                <p>
                                    Zapomnij o czasochłonnym szukaniu odpowiedniej oferty. Zaufaj nam i przekonaj się, że szukanie nieruchomości jeszcze nigdy nie było tak proste. 
                                 </p>
                                 <p>
                                    Każdy doradca posiada swój profil na którym znajdują się komentarze od Klientów , dzięki czemu masz pewność, że współpracujesz z właściwą osobą. Oceny wystawiane po zakończeniu każdej transakcji to gwarancja jakości i profesjonalizmu.
                                </p>
                            </div>
                            
                        </div><!--
                        --><div class="col-md-6 col-sm-12 vbottom">
                            <div class="block wow fadeInRight" data-wow-delay=".3s" data-wow-duration="500ms">
                            <p></p>
                                <img
        border:0;" src="{% static 'images/zdm-doradcy.jpg' %}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </section> <!-- /#about -->
{% endblock %}

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html class="no-js">
    <head>
        <!-- Meta -->
        {% include 'meta.html' %}
        <!-- CSS Files -->
        {% include 'css.html' %}
        <!-- JavaScript -->
        {% include 'javascript.html' %}
    </head>
    <body>
        <!-- Header -->
        {% include 'header.html' %}
        <section id="messages">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} ">  <!-- singular -->
                                <a class="close" data-dismiss="alert">×</a>
                                {{ message|safe }}
                            </div>
                        {% endfor %}
                        {% endif %}   
                    </div>
                </div>
            </div>
        </section>                      
        {% block content %}
        {% endblock %}                
        <!-- CTA -->
        <section id="call-to-action">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="block">
                            <h2 class="title wow fadeInDown" data-wow-delay=".3s" data-wow-duration="500ms">Szukasz mieszkania, lokalu czy domu?</h1>
                            <p class="wow fadeInDown" data-wow-delay=".5s" data-wow-duration="500ms">Przeglądanie ofert zabiera Ci sporo czasu, a na koniec i tak musisz zapłacić prowizję dla biura nieruchomości, mimo tego, że sam znalazłeś ofertę. Pośrednik jedynie pokazał Ci nieruchomość, a większość formalności i tak musisz załatwić sam?</p> 

                            <p class="wow fadeInDown" data-wow-delay=".5s" data-wow-duration="500ms">Znaleźliśmy dla Ciebie lepsze rozwiązanie. Zacznij od końca. Znajdź pośrednika nieruchomości, który przygotuje dla Ciebie najlepsze, indywidualnie dobrane oferty oraz pomoże załatwić wszelkie formalności.</p>
                            <a href="{% url 'contact' %}" class="btn btn-default btn-contact wow fadeInDown" data-wow-delay=".7s" data-wow-duration="500ms">Otrzymaj darmowe oferty</a>
                        </div>
                    </div>
                    
                </div>
            </div>
        </section>
        <!-- Footer -->
        <footer id="footer">
            <div class="container">
                <div class="col-md-8">
                    <p class="copyright">&copy; <span>2017</span>    <a href="{% url 'home' %}" >
                        <span style="color: #000">IDEALNY</span><span style="color: #fd5e29"> POŚREDNIK.</span>
                    </a> Wszelkie prawa zastrzeżone. <a href="{% url 'policy' %}">Polityka prywatności</a> • <a href="{% url 'toc' %}">Regulamin</a>
                </div>
                <div class="col-md-4">
                    <!-- Social Media -->
                    <ul class="social">
                        <li>
                            <a href="#" class="Facebook">
                                <i class="ion-social-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="Twitter">
                                <i class="ion-social-twitter"></i>
                            </a>
                        </li>
                        <!--<li>
                            <a href="#" class="Linkedin">
                                <i class="ion-social-linkedin"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="Google Plus">
                                <i class="ion-social-googleplus"></i>
                            </a>
                        </li>-->
                    </ul>
                </div>
            </div>
        </footer>
        {% block extra_body %}
        {% endblock %}  
        <!--<script>
            $(function() {
            $('.block').matchHeight();
            });
        </script>--> 
    </body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block title %}Znajdź mi nieruchmość{{ block.super }}{% endblock %}

{% block content%}
         <section id="page" class="pico">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 vbottom">
                            <div class="block wow fadeInLeft" data-wow-delay=".3s" data-wow-duration="500ms">
                                <h2>
                               Wypełnij formularz i opisz nieruchomość
                                </h2>
                                <p> Wypełnij formularz i określ nam w kilku zdaniach typ nieruchomości jakiej szukasz. Znajdziemy dla Ciebie trzech pośredników, którzy przygotują darmowe oferty. To ty decydujesz, z którym pośrednikiem nieruchomości będziesz współpracował.</p>
                                <form role="form" action="" method="post">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <button type="submit" class="btn btn-default">Wyślij wiadomość</button>
                                    <br><br>
                                    <p><i class="ion-locked" style="color: #fd5e29; padding-right: 5px;"></i>Informacje przesyłane i odbierane na tej stronie są prywatne.</p>
                                </form>
                            </div>
                            
                        </div><!--
                        --><div class="col-md-6 col-sm-12 vbottom">
                            <div class="block wow fadeInRight" data-wow-delay=".3s" data-wow-duration="500ms">
                                <img src="{% static 'images/zmd-formularz.jpg' %}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </section>
{% endblock %}

templates/css.html
{% load static from staticfiles %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!-- Ionicons Fonts Css -->
<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
<!-- animate css -->
<link rel="stylesheet" href="{% static 'css/animate.css' %}">
 <!-- Hero area slider css-->
<link rel="stylesheet" href="{% static 'css/slider.css' %}">
<!-- template main css file -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<!-- responsive css -->
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

templates/header.html
{% load static from staticfiles %}
<header id="top-bar" class="navbar-fixed-top animated-header">
    <div class="container">
        <div class="navbar-header">
            <!-- responsive nav button -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <!-- /responsive nav button -->
            <!-- logo -->
            <div class="navbar-brand">
                <a href="{% url 'home' %}" >
                    <span style="color: #000; font-weight: 400;">IDEALNY</span><span style="color: #fd5e29; font-weight: 400;"> POŚREDNIK</span>
                    <span style="color: #000; font-weight: 400; font-size: 10px;"> BETA</span>
                </a>
            </div>
            <!-- /logo -->
        </div>
        <!-- main menu -->
        <nav class="collapse navbar-collapse navbar-right" role="navigation">
            <div class="main-menu">
                <ul class="nav navbar-nav navbar-right">
                    <li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}>
                        <a href="{% url 'home' %}" >Start</a>
                    </li>
                    <li {% if request.resolver_match.url_name == 'list' %}class="active"{% endif %}><a href="{% url 'profiles:list' %}">Pośrednicy</a></li>
                    <li {% if request.resolver_match.url_name == 'about' %}class="active"{% endif %}><a href="{% url 'about' %}">O nas</a></li>
                    <li {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}><a href="{% url 'contact' %}">Otrzymaj darmowe oferty</a></li>
                    {% if user.is_authenticated %}
					  <li class="dropdown">
                        <a href="{% url 'panel' %}" class="dropdown-toggle btn-panel">{{ user.get_full_name }} <span class="caret"></span></a>
                        <div class="dropdown-menu">
                            <ul>
                                <li><a href="{% url 'panel' %}">Panel</a>
                                <li><a href="{% url 'account_email' %}">Zmień E-Mail</a></li>
                                <li><a href="{% url 'account_logout' %}">Wyloguj się</a></li>
                            </ul>
                        </div>
                        </li>
                        <li>
                        {% if user.profile.avatar %}
                
                        <img src="{{ user.profile.avatar.url}}" id="profil-nav" class="img-responsive" alt="{{ profile.user.get_full_name }}" width=52>
                
                        {% else %}
                
                        <img src="{% static 'images/avatar-default.jpg' %}" id="profil-nav" class="img-responsive" alt="{{ profile.user.get_full_name }}" width=52>
               
                        {% endif %}  

                        </li>
					{% else %}
					    
                        <li {% if request.resolver_match.url_name == 'account_signup' %}class="dropdown active"{% else %} class="dropdown"{% endif %}>
                            <a href="{% url 'account_signup' %}">Jesteś pośrednikiem?</a>
                            <div class="dropdown-menu">
                                <ul>
                                    <li><a href="{% url 'account_signup' %}"">Zarejestruj się</a></li>
                                    <li {% if request.resolver_match.url_name == 'account_login' %}class="active"{% endif %}><a href="{% url 'account_login' %}">Zaloguj się</a></li>
                                </ul>
                            </div>
                        </li> 
					{% endif %}
                    
                </ul>
            </div>
        </nav>
        <!-- /main nav -->
    </div>
</header>

templates/home.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %}Home {{ block.super }}{% endblock %}

{% block content%}
<section id="hero-area" >
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="block wow fadeInUp" data-wow-delay=".3s">
                    <section class="cd-intro">
                        <h1 class="wow fadeInUp animated cd-headline slide" data-wow-delay=".4s" >
                            <span>3 KROKI DO TWOJEGO</span><br>
                            <span class="cd-words-wrapper">
                                <b class="is-visible">DOMU</b>
                                <b>MIESZKANIA</b>
                                <b>LOKALU</b>
                            </span>
                        </h1>
                    </section> 
                    <h2 class="wow fadeInUp animated" data-wow-delay=".6s" >
                        Decydując się na zakup mieszkania, musisz liczyć się z zapłatą prowizji dla biura nieruchomości. <br>Nie

trać czasu na przeglądanie ofert , niech zrobi to za Ciebie <br>profesjonalny pośrednik nieruchomości.
                    </h2>
                    <a class="btn-lines dark light wow fadeInUp animated btn btn-default" data-wow-delay=".9s" href="{% url 'contact' %}">Otrzymaj darmowe oferty</a>       
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="service-page" class="pages service-page"> 
      <div class="container">
		<div class="row service-parts">
            <div class="col-md-4">
                <div class="block wow fadeInUp animated" data-wow-duration="400ms" data-wow-delay="600ms">
                    <i class="ion-ios-person-outline"></i>
                    <h4>WYPEŁNIJ FORMULARZ</h4>
                    <p>Wypełnij formularz i określ nam w kilku zdaniach typ nieruchomości jakiej szukasz.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="block wow fadeInUp animated" data-wow-duration="400ms" data-wow-delay="800ms">
                    <i class="ion-ios-compose-outline"></i>
                    <h4>ZNAJDZIEMY DLA CIEBIE POŚREDNIKÓW</h4>
                    <p>Znajdziemy dla Ciebie trzech pośredników nieruchomości, którzy przygotują najlepsze propozycje.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="block wow fadeInUp animated" data-wow-duration="400ms" data-wow-delay="1s">
                    <i class="ion-ios-paper-outline"></i>
                    <h4>OFERTA</h4>
                    <p>Pośrednicy przygotują oferty. To ty decydujesz, z którym pośrednikiem nieruchomości będziesz współpracował.</p>
                </div>
            </div>
        </div>
      </div>  
    </section>
{% endblock %}

templates/javascript.html
{% load static from staticfiles %}
<script src="{% static 'js/vendor/modernizr-2.6.2.min.js' %}"></script>
<!-- jquery -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- bootstrap js -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- wow js -->
<script src="{% static 'js/wow.min.js' %}"></script>
 <!-- slider js -->
<script src="{% static 'js/slider.js' %}"></script>
<!-- template main js -->
<script src="{% static 'js/main.js' %}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.matchHeight/0.7.0/jquery.matchHeight-min.js"></script>

templates/meta.html
{% load static from staticfiles %}
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="icon" type="image/png" href="{% static 'images/favicon.ico' %}">
<title>Idealny Pośrednik</title>
<meta name="description" content="Wybierz doradcę, wypełnij formularz i otrzymaj najlepsze oferty. Tylko profesjonalny doradca zapewni Tobie pewny i bezpieczny zakup nieruchomośći.">
<!-- Mobile Specific Metas -->
<meta name="format-detection" content="telephone=no">
<meta name="viewport" content="width=device-width, initial-scale=1">

templates/panel.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %}Panel{{ block.super }}{% endblock %}

{% block content%}
         <section id="page">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="block wow fadeInDown" data-wow-delay=".3s" data-wow-duration="500ms">
                                <h2>Panel</h2>
                            </div>
                        </div>
                    </div>        
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="block wow fadeInLeft" data-wow-delay=".3s" data-wow-duration="500ms">
                               
                                {% if user == request.user %}
                                <h3>Witaj {{ user.get_full_name }}  </h3>
                                <p>
									Zakładając konto jako pośrednik nieruchmości na platformie Idealny Pośrednik otrzymujesz do dyspozycji profil doradcy, system opini oraz możliwość pozyskania nowych klientów.
                                </p>
                                <p>
                                    Tylko pełne profile zawierające komplet danych zostaną wyświetlone w dziale Pośrednicy, dlatego polecamy jak najszybsze wypełnienie profilu. 
                                </p>
                              
                                
                                    <a href="{% url 'profiles:detail' pk=profile.pk %}" class="btn btn-block btn-default">Przejdź do profilu</a>
                                
                                    <p></p>    
                                
                                    <a href="{% url 'profiles:edit' pk=profile.pk %}" class="btn btn-block btn-default">Przejdź do edycji profilu</a>
                                
                                {% endif %}


                            </div>          
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="block wow fadeInRight" data-wow-delay=".3s" data-wow-duration="500ms">
                               
                                <h3 >Opinie({{ profile.get_approved_reviews.count }})</h3>
                                {% if profile.get_approved_reviews %}
                                    {% for review in profile.get_approved_reviews|slice:":6" %}
                                                 <ul class="item">
                                                       <li> {{ review.name }} - {{ review.message|truncatewords_html:15 }}</li>  
                                                </ul>
                                    {% endfor %}
                                {% else %}
                                <p>Ten doradca nie otrzymał jeszcze opini.</p>
                                {% endif %}
                                  <a href="{% url 'profiles:detail' pk=profile.pk %}" class="btn btn-block btn-default">Zobacz wszystkie opinie na profilu</a>
                               <!-- <h3 >Wiadomosci({{ profile.get_inquiries.count }})</h3>
                                {% if profile.get_inquiries %}
                                    {% for inquiry in profile.get_inquiries|slice:":3" %}
                                                 <ul class="item">
                                                       <li> {{ inquiry.name }} - {{ inquiry.message|truncatewords_html:15 }}</li>  
                                                </ul>
                                    {% endfor %}
                                {% else %}
                                <p>Ten doradca nie otrzymał jeszcze wiadomości.</p>
                                {% endif %}
                                  <a href="{% url 'profiles:detail' pk=profile.pk %}" class="btn btn-block btn-default">Zobacz wszystkie wiadomości na profilu</a>-->
                            </div>    
                        </div>
                    </div>
                </div>
            </section>
{% endblock %}

templates/policy.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}Polityka prywatności {{ block.super }}{% endblock %}
{% block content%}
<section id="page" class="pico">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="block wow fadeInLeft" data-wow-delay=".3s" data-wow-duration="500ms">
                    <h2>
                    Polityka prywatności serwisu Idealny Pośrednik
                    </h2>
                    <h3>Informacje ogólne.</h3>
                    <p>
                    1. Operatorem Serwisu Idealny Pośrednik jest: CONCA Agnieszka Nowińska
                    <br>
                    2. Serwis realizuje funkcje pozyskiwania informacji o użytkownikach i ich zachowaniu w następujący sposób:<br>
                    &nbsp;&nbsp;a.  Poprzez dobrowolnie wprowadzone w formularzach informacje.<br> 
                    &nbsp;&nbsp;b.  Poprzez zapisywanie w urządzeniach końcowych pliki cookie (tzw. "ciasteczka").
                    </p>
                    <h3> Informacje w formularzach.</h3>
                    <p>
                    1.  Serwis zbiera informacje podane dobrowolnie przez użytkownika.<br>
                    2.  Serwis może zapisać ponadto informacje o parametrach połączenia (oznaczenie czasu, adres IP).<br>
                    3.  Dane w formularzu nie są udostępniane podmiotom trzecim inaczej, niż za zgodą użytkownika.<br>
                    4.  Dane podane w formularzu są przetwarzane w celu wynikającym z funkcji konkretnego formularza, np w celu dokonania procesu obsługi zgłoszenia serwisowego lub kontaktu handlowego.
                    </p>
                    <h3>Informacja o plikach cookies.</h3>
                    <p>
                    1.  Serwis korzysta z plików cookies.<br>
                    2.  Pliki cookies (tzw. „ciasteczka”) stanowią dane informatyczne, w szczególności pliki tekstowe, które przechowywane są w urządzeniu końcowym Użytkownika Serwisu i przeznaczone są do korzystania ze stron internetowych Serwisu. Cookies zazwyczaj zawierają nazwę strony internetowej, z której pochodzą, czas przechowywania ich na urządzeniu końcowym oraz unikalny numer.<br>
                    3.  Podmiotem zamieszczającym na urządzeniu końcowym Użytkownika Serwisu pliki cookies oraz uzyskującym do nich dostęp jest operator Serwisu.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section> 
{% endblock %}

templates/toc.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %}Regulamin {{ block.super }}{% endblock %}

{% block content%}
<section id="page" class="pico">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="block wow fadeInLeft" data-wow-delay=".3s" data-wow-duration="500ms">
                    <h2>
                    Regulamin
                    </h2>
                    
                    <p>
                        Serwis idealnyposrednik.pl jest obecnie dostępny w wersji testowej(wersja beta).
                    <p>
                        Regulamin serwisu będzie dostępny wraz z opublikowaniem wersji finałowej.
                    </p>
                    <p>
                        Operatorem Serwisu Idealny Pośrednik jest: CONCA Agnieszka Nowińska
                    </p>
                    <h3> Informacje w formularzach.</h3>
                    <p>
                        1.  Serwis zbiera informacje podane dobrowolnie przez użytkownika.<br>
                    2.  Serwis może zapisać ponadto informacje o parametrach połączenia (oznaczenie czasu, adres IP).<br>
                    3.  Dane w formularzu nie są udostępniane podmiotom trzecim inaczej, niż za zgodą użytkownika.<br>
                    4.  Dane podane w formularzu są przetwarzane w celu wynikającym z funkcji konkretnego formularza, np w celu dokonania procesu obsługi zgłoszenia serwisowego lub kontaktu handlowego.
                    </p>
                    <p>
                        Kontakt: <a href="mailto:biuro@idealnyposrednik.pl">biuro@idealnyposrednik.pl</a>
                    </p>
                </div>
                
            </div>

        </div>
    </div>
</section> 
{% endblock %}